variable "env_prefix" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "allocated_storage" {}
variable "instance_class" {}
variable "subnet_ids" {}
variable "app_name" {}
variable "eb_security_group_id" {}
variable "postgres_port" {}
