variable "region" {}
variable "vpc_cidr_block" {}
variable "subnet_cidr_block_1" {}
variable "subnet_cidr_block_2" {}
variable "avail_zone_1" {}
variable "avail_zone_2" {}
variable "env_prefix" {}
variable "app_name" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "allocated_storage" {}
variable "instance_class" {}
variable "app_port" {}
variable "postgres_port" {}
variable "docker_img_tag" {}
variable "jwt_secret" {}
variable "frontend_domain" {}
variable "email_name" {}
variable "email_from" {}
variable "admin_email" {}
variable "admin_initial_password" {}
variable "bucket_name" {}
