variable "vpc_cidr_block" {}
variable "subnet_cidr_block_1" {}
variable "subnet_cidr_block_2" {}
variable "avail_zone_1" {}
variable "avail_zone_2" {}
variable "env_prefix" {}
variable "app_name" {}
variable "app_port" {}
variable "postgres_port" {}
