variable "env_prefix" {}
variable "app_name" {}
variable "ecr_repo_url" {}
variable "rds_endpoint" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "security_groups" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "app_port" {}
variable "postgres_port" {}
variable "docker_img_tag" {}
variable "region" {}
variable "jwt_secret" {}
variable "frontend_domain" {}
variable "email_name" {}
variable "email_from" {}
variable "admin_email" {}
variable "admin_initial_password" {}
variable "bucket_name" {}